### ISSUE TITLE
SQLAlchemy TypeError: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by Stoltzman** [snowflakedb/snowflake-sqlalchemy#163] opened 2020-03-06 16:13 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.8.1
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.16299-SP0
3. What are the component versions in the environment (`pip list`)? 
Package                       Version
----------------------------- ----------
altair                        4.0.1
antlr4-python2-runtime        4.7.1
appdirs                       1.4.3
asn1crypto                    1.3.0
atomicwrites                  1.1.5
attrs                         18.1.0
autopep8                      1.5
azure-common                  1.1.24
azure-storage-blob            2.1.0
azure-storage-common          2.1.0
backcall                      0.1.0
backports.functools-lru-cache 1.6.1
bleach                        3.1.1
boto3                         1.11.17
botocore                      1.14.17
certifi                       2019.11.28
cffi                          1.13.2
chardet                       3.0.4
Click                         7.0
colorama                      0.4.3
coverage                      5.0.3
cryptography                  2.8
decorator                     4.4.1
defusedxml                    0.6.0
distlib                       0.3.0
docutils                      0.15.2
elasticsearch                 6.4.0
entrypoints                   0.3
filelock                      3.0.12
flake8                        3.5.0
flake8-tidy-imports           1.1.0
future                        0.18.2
httplib2                      0.9.2
idna                          2.8
ijson                         2.6.1
ipykernel                     5.1.4
ipython                       7.12.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
jedi                          0.16.0
Jinja2                        2.11.1
jmespath                      0.9.5
jsonschema                    3.2.0
jupyter-client                6.0.0
jupyter-core                  4.6.3
MarkupSafe                    1.1.1
marshmallow                   2.20.5
mccabe                        0.6.1
mistune                       0.8.4
mock                          2.0.0
more-itertools                4.2.0
nbconvert                     5.6.1
nbformat                      5.0.4
neo4j-driver                  1.7.2
neobolt                       1.7.16
neotime                       1.7.1
notebook                      6.0.3
numpy                         1.18.1
oscrypto                      1.2.0
pandas                        1.0.1
pandocfilters                 1.4.2
parso                         0.6.2
pbr                           5.4.4
pickleshare                   0.7.5
pip                           20.0.2
pluggy                        0.13.1
prometheus-client             0.7.1
prompt-toolkit                3.0.3
psutil                        5.7.0
py                            1.5.3
pycodestyle                   2.5.0
pycparser                     2.19
pycryptodomex                 3.9.7
pyflakes                      1.6.0
Pygments                      2.5.2
pyhocon                       0.3.42
PyJWT                         1.7.1
pyOpenSSL                     19.1.0
pyparsing                     2.2.0
pyrsistent                    0.15.7
pytest                        3.10.1
pytest-cov                    2.8.1
pytest-mock                   1.13.0
python-dateutil               2.8.1
pytz                          2018.4
pywin32                       227
pywinpty                      0.5.7
pyzmq                         19.0.0
requests                      2.22.0
retrying                      1.3.3
ruamel.yaml                   0.16.10
ruamel.yaml.clib              0.2.0
s3transfer                    0.3.3
scipy                         1.4.1
Send2Trash                    1.5.0
setuptools                    41.2.0
six                           1.14.0
snowflake-connector-python    2.2.1
snowflake-sqlalchemy          1.2.1
SQLAlchemy                    1.3.13
statsd                        3.2.1
stevedore                     1.32.0
termcolor                     1.1.0
terminado                     0.8.3
testpath                      0.4.4
toolz                         0.10.0
tornado                       6.0.3
traitlets                     4.3.3
typing                        3.6.4
tzlocal                       2.0.0
Unidecode                     1.1.1
urllib3                       1.25.8
virtualenv                    20.0.7
virtualenv-clone              0.5.3
virtualenvwrapper-win         1.2.6
wcwidth                       0.1.8
webencodings                  0.5.1
wheel                         0.31.1
widgetsnbextension            3.5.1
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

5. What did you expect to see?
Executing a batch in in Great_expectations which uses SQLAlchemy. The batch works OK for regular tables However when trying a batch on a view it fails due to the generated query in SF seem to be wrong.

 SHOW /* sqlalchemy:get_table_comment */ VIEWS LIKE 'dim_portfolio' IN SCHEMA datamart

6. What did you see instead?
 SHOW /* sqlalchemy:get_table_comment */ TABLES LIKE 'dim_portfolio' IN SCHEMA datamart

7. Can you set logging to DEBUG and collect the logs?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-804edf7342f8> in <module>
     11 
     12 batch = context.get_batch(batch_kwargs, expectation_suite_name)
---> 13 batch.head()
     14 
c:\users\mist\envs\ge_sf\lib\site-packages\great_expectations\dataset\sqlalchemy_dataset.py in head(self, n)
    326 
    327         try:
--> 328             df = next(pd.read_sql_table(
    329                 table_name=self._table.name,
    330                 schema=self._table.schema,
c:\users\mist\envs\ge_sf\lib\site-packages\pandas\io\sql.py in read_sql_table(table_name, con, schema, index_col, coerce_float, parse_dates, columns, chunksize)
    240     meta = MetaData(con, schema=schema)
    241     try:
--> 242         meta.reflect(only=[table_name], views=True)
    243     except sqlalchemy.exc.InvalidRequestError:
    244         raise ValueError(f"Table {table_name} not found")
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\sql\schema.py in reflect(self, bind, schema, views, only, extend_existing, autoload_replace, resolve_fks, **dialect_kwargs)
   4269             for name in load:
   4270                 try:
-> 4271                     Table(name, self, **reflect_opts)
   4272                 except exc.UnreflectableTableError as uerr:
   4273                     util.warn("Skipping table %s: %s" % (name, uerr))
<string> in __new__(cls, *args, **kw)
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\util\deprecations.py in warned(fn, *args, **kwargs)
    126                     )
    127 
--> 128             return fn(*args, **kwargs)
    129 
    130         doc = fn.__doc__ is not None and fn.__doc__ or ""
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\sql\schema.py in __new__(cls, *args, **kw)
    504             except:
    505                 with util.safe_reraise():
--> 506                     metadata._remove_table(name, schema)
    507 
    508     @property
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     66             self._exc_info = None  # remove potential circular references
     67             if not self.warn_only:
---> 68                 compat.reraise(exc_type, exc_value, exc_tb)
     69         else:
     70             if not compat.py3k and self._exc_info and self._exc_info[1]:
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\util\compat.py in reraise(tp, value, tb, cause)
    151         if value.__traceback__ is not tb:
    152             raise value.with_traceback(tb)
--> 153         raise value
    154 
    155     def u(s):
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\sql\schema.py in __new__(cls, *args, **kw)
    499             metadata._add_table(name, schema, table)
    500             try:
--> 501                 table._init(name, metadata, *args, **kw)
    502                 table.dispatch.after_parent_attach(table, metadata)
    503                 return table
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\sql\schema.py in _init(self, name, metadata, *args, **kwargs)
    588         # circular foreign keys
    589         if autoload:
--> 590             self._autoload(
    591                 metadata,
    592                 autoload_with,
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\sql\schema.py in _autoload(self, metadata, autoload_with, include_columns, exclude_columns, resolve_fks, _extend_on)
    611 
    612         if autoload_with:
--> 613             autoload_with.run_callable(
    614                 autoload_with.dialect.reflecttable,
    615                 self,
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\engine\base.py in run_callable(self, callable_, *args, **kwargs)
   1613 
   1614         """
-> 1615         return callable_(self, *args, **kwargs)
   1616 
   1617     def _run_visitor(self, visitorcallable, element, **kwargs):
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\engine\default.py in reflecttable(self, connection, table, include_columns, exclude_columns, resolve_fks, **opts)
    464     ):
    465         insp = reflection.Inspector.from_engine(connection)
--> 466         return insp.reflecttable(
    467             table, include_columns, exclude_columns, resolve_fks, **opts
    468         )
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\engine\reflection.py in reflecttable(self, table, include_columns, exclude_columns, resolve_fks, _extend_on)
    700         )
    701 
--> 702         self._reflect_table_comment(
    703             table_name, schema, table, reflection_options
    704         )
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\engine\reflection.py in _reflect_table_comment(self, table_name, schema, table, reflection_options)
   1003     ):
   1004         try:
-> 1005             comment_dict = self.get_table_comment(table_name, schema)
   1006         except NotImplementedError:
   1007             return
c:\users\mist\envs\ge_sf\lib\site-packages\sqlalchemy\engine\reflection.py in get_table_comment(self, table_name, schema, **kw)
    533         """
    534 
--> 535         return self.dialect.get_table_comment(
    536             self.bind, table_name, schema, info_cache=self.info_cache, **kw
    537         )
c:\users\mist\envs\ge_sf\lib\site-packages\snowflake\sqlalchemy\snowdialect.py in get_table_comment(self, connection, table_name, schema, **kw)
    584         cursor = connection.execute(sql_command)
    585         ans = cursor.fetchone()
--> 586         return {'text': ans['comment'] if ans['comment'] else None}
    587 
    588 
TypeError: 'NoneType' object is not subscriptable

**Comment by Stoltzman** [comment] 2020-03-09 09:35
The fix in in the return statement as suggested in #164 solved it!

**Comment by keller00** [comment] 2020-03-09 16:14
Closing this, duplicate of #164

**Closed by keller00** 2020-03-09 16:14 UTC
