### ISSUE TITLE
SNOW-799302: issue with executing query containing % character with snowflake

### ISSUE THREAD

**Issue by phanikumv** [snowflakedb/snowflake-sqlalchemy#408] opened 2023-04-21 04:57 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.9.16

2. What operating system and processor architecture are you using?

   Linux-5.15.49-linuxkit-aarch64-with-glibc2.31

3. What are the component versions in the environment (`pip freeze`)?

   snowflake-sqlalchemy==1.4.7
   SQLAlchemy==1.4.47

4. What did you do?

   execute the below query
   `SELECT CASE WHEN NAME ILIKE '%b%' THEN 'a' ELSE 'b' END AS test FROM PROVIDERS_FIVETRAN_DEV.S3.FIVETRAN_ANKIT_TEST;`
   

5. What did you expect to see?

   What should have happened and what happened instead?
   
   Expect the query to get successfully execute. Instead we see the below error
     `File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 695, in execute
    query = self._preprocess_pyformat_query(command, params)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 594, in _preprocess_pyformat_query
    query = command % processed_params
ValueError: unsupported format character 'b' (0x62) at index 30`

**Comment by sfc-gh-dszmolka** [comment] 2024-03-18 11:24
hi and apologies for leaving this issue unattended for so long, we're changing this going forward.

using snowflake-sqlalchemy 1.5.1 with the latest PythonConnector available today (3.7.1) works for me.
```python
#!/usr/bin/env python
from sqlalchemy import create_engine

engine = create_engine(
    'snowflake://{user}:{password}@{account_identifier}/{db}/{schema}?warehouse={wh}'.format(
        user=...
        password=...,
        account_identifier=...,
        db='TEST_DB',
        schema='PUBLIC',
        wh='COMPUTE_WH',
    )
)
query = "select case when B ilike '%row1%' then '1' when B ilike '%row2%' then '2' end as test from test_db.public.t001;"
try:
    connection = engine.connect()
    results = connection.execute(query).fetchone()
    print(results[0])
finally:
    connection.close()
    engine.dispose()
```

results in
```
# python test.py 
/test/test.py:17: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  results = connection.execute(query).fetchone()
1
```

seems to be fixed so i'm closing this now.

if it still doesn't work for you, could you please provide a code snippet which reproduces the issue ? we can then look further. thank you !

**Closed by sfc-gh-dszmolka** 2024-03-18 11:24 UTC
Labels: bug, needs triage, status-triage
