### ISSUE TITLE
SNOW-538310: Error when using `create_engine()` and password containing `%` character

### ISSUE THREAD

**Issue by marcomasulli** [snowflakedb/snowflake-sqlalchemy#268] opened 2022-01-31 09:44 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? 3.8.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)? Windows-10-10.0.19041-SP0

3. What are the component versions in the environment (`pip list`)? 
```
Package                    Version
-------------------------- ---------
asn1crypto                 1.4.0
certifi                    2021.10.8
cffi                       1.15.0
charset-normalizer         2.0.10
cryptography               36.0.1
greenlet                   1.1.2
idna                       3.3
oscrypto                   1.2.1
pip                        20.2.1
pycparser                  2.21
pycryptodomex              3.12.0
PyJWT                      2.3.0
pyOpenSSL                  21.0.0
pytz                       2021.3
requests                   2.27.1
setuptools                 49.2.1
six                        1.16.0
snowflake-connector-python 2.7.3
snowflake-sqlalchemy       1.3.3
SQLAlchemy                 1.4.31
urllib3                    1.26.8
```
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Trying to create an engine using a password that contains a % character.
```
LOGIN_NAME = "login"
PASSWORD = "pass%word"
ACCOUNT_NAME = "account"

connection_string = f'snowflake://{LOGIN_NAME}:{PASSWORD}@{ACCOUNT_NAME}/'

engine = create_engine(connection_string, echo=True)

try:
    conn = engine.connect() 
    results = conn.execute('select current_version()').fetchone()
    print(results[0])
finally:
    conn.close()
    engine.dispose()
```
5. What did you expect to see?

printing `6.1.1` on the terminal

6. What did you see instead?
```
sqlalchemy.exc.DatabaseError: (snowflake.connector.errors.DatabaseError) 250001 (08001): None: Failed to connect to DB: xxxxxxxxx.snowflakecomputing.com:443. Incorrect username or password was specified.
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```
7. Can you set logging to DEBUG and collect the logs?

Unfortunately I cannot post logs.

The same credentials allow to connect successfully by using the `snowflake` `connector`:

```
from snowflake import connector

connSF = connector.connect(
                role=role,
                user=user,
                account=account,
                password=password,
                warehouse=warehouse)
```

Other credentials (where password does not contain a % character) yield a positive result using the `sqlalchemy` `create_engine` technique.

I tried several routes, including using urllib.parse.quote_plus() to create the connection string, however this yields a "User empty" error.

**Comment by philippeboyd** [comment] 2022-03-30 15:46
We had the same issue, here's a workaround: 

```python
connection_string = f'snowflake://{LOGIN_NAME}:{PASSWORD.replace("%", "%%")}@{ACCOUNT_NAME}/'
```

**Comment by pratik-rao-official** [comment] 2022-07-27 16:35
Facing the same issue. Password has '%'. Tried the replace option but doesn't work. snowflake.connector is able to connect with the same credentials. SQLAlchemy is unable to.

**Comment by sfc-gh-aling** [comment] 2022-08-01 17:27
hey folks, sorry for keeping you waiting here. We have fixed double percent issue in the latest release 1.4.0.
could you try upgrading to the latest version `pip install snowflake-sqlalchemy --upgrade` to see if the fix works for you?

**Comment by alexscott-ff** [comment] 2022-08-10 02:26
This was happening to me too but with an `@` symbol. I used `urllib.parse.quote_plus` around it and it worked.

**Comment by sfc-gh-aling** [comment] 2022-08-16 18:15
hey folks, I have found the root cause for it.

This is a by-design behavior of sqlalchemy as pointed out: https://docs.sqlalchemy.org/en/14/core/engines.html#escaping-special-characters-such-as-signs-in-passwords.

The password containing special characters like `@` or `%` has to be escaped to be processed properly. as @alexscott-ff mentioned (thanks alexscott-ff), you could use `urllib.parse.quote_plus` to encode the password first.

I've updated the readme to include instructions on how to tackle this: https://github.com/snowflakedb/snowflake-sqlalchemy/pull/338.

**Comment by sfc-gh-aling** [comment] 2022-08-16 18:42
The PR has been merged, I'm closing the issue now, thanks for your feedbacks!

**Closed by sfc-gh-aling** 2022-08-16 18:42 UTC
