### ISSUE TITLE
insert with autoincrement fails with sqlalchemy.exc.ArgumentError

### ISSUE THREAD

**Issue by ynux** [snowflakedb/snowflake-sqlalchemy#124] opened 2019-10-24 14:31 UTC
## What did I do

Create a table with an autoincrement  column as in your [README](https://github.com/snowflakedb/snowflake-sqlalchemy#auto-increment-behavior) . Then fetch the table into a new MetaData object and insert, relying on autoincrement / no value for that column.

### What did I expect

A row to be created, with the autoincrement column filled from the sequence

### Error

sqlalchemy.exc.ArgumentError: Column type DECIMAL(38, 0) on column 'sequencetable.id' is not compatible with autoincrement=True

### Reproduce

```
metadata = MetaData()
t1 = Table('sequencetable', metadata,
    Column('id', Integer, Sequence('id_seq'), primary_key=True),
    Column('data', String(39))
)

t1.create(engine)

### this works
connection.execute(t1.insert(), [ {'data': 'test_insert'}])

select_stmt_t1 = select([t1])
connection.execute(select_stmt_t1).fetchall()

metadata2 = MetaData()
t2 = Table('sequencetable', metadata2, autoload=True, autoload_with=engine)

### this fails 
connection.execute(t2.insert(), [ {'data': 'multi_insert_1'}, {'data': 'multi_insert_2'} ])
connection.execute(t2.insert(), [ {'data': 'test_insert'}])

### this works
seq = Sequence('id_seq')
nextid = connection.execute(seq)
connection.execute(t2.insert(), [ {'id': nextid, 'data': 'test_insert'}])

```
Remark: The above code stopped working for me now. When I create the table, it fails with 

```
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 090106 (22000): Cannot perform CREATE SEQUENCE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[SQL: CREATE SEQUENCE id_seq]
```
As a workaround I will create and use the sequence explicitly.

While you are at it, maybe correct the `autoinrecment` typo in your tests.

### Version info
Python 3.7.4
Darwin-18.7.0-x86_64-i386-64bit
```
Package                    Version  
-------------------------- ---------
asn1crypto                 1.2.0    
azure-common               1.1.23   
azure-storage-blob         2.1.0    
azure-storage-common       2.1.0    
boto3                      1.9.253  
botocore                   1.12.253 
certifi                    2019.9.11
cffi                       1.13.1   
chardet                    3.0.4    
cryptography               2.8      
docutils                   0.15.2   
future                     0.18.1   
idna                       2.8      
ijson                      2.5.1    
jmespath                   0.9.4    
oscrypto                   1.1.0    
pip                        19.3.1   
pycparser                  2.19     
pycryptodomex              3.9.0    
PyJWT                      1.7.1    
pyOpenSSL                  19.0.0   
python-dateutil            2.8.0    
pytz                       2019.3   
requests                   2.22.0   
s3transfer                 0.2.1    
setuptools                 41.4.0   
six                        1.12.0   
snowflake-connector-python 2.0.2    
snowflake-sqlalchemy       1.1.16   
SQLAlchemy                 1.3.10   
urllib3                    1.25.6   
wheel                      0.33.6   
```

**Comment by smtakeda** [comment] 2019-10-24 18:58
oh, thanks for pointing out the typos. Will fix them.

As far as I investigated, `autoincrement=True` doesn't work in general mainly because no last inserted id is supported by Snowflake.

**Comment by ynux** [comment] 2019-10-24 21:19
I agree, autoincrement=True gets ignored.

**Comment by keller00** [comment] 2019-12-10 18:51
@ynux could you try removing the list itself, I just checked sqlalchemy documentation and found [here](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.Connection.execute.params.*multiparams/**params) that you should be doing:
```
connection.execute(t2.insert(), {'data': 'multi_insert_1'}, {'data': 'multi_insert_2'})
```
This works for me

**Comment by ynux** [comment] 2020-01-08 13:19
Sorry, but your command throws the same error when done on the t2 (with metadata2) if you exactly follow my steps. It works with t1 / metatdata. Maybe I should have put more emphasis on the part that I suspect to be the issue: The reflected metadata2. Things work as long as you work with the metadata from the table creation. But when you reflect the table back from an existing table with a sequence, as in my line `metadata2 = MetaData()` , something in this Metadata seems to be broken. This is already visible when you do a `print(CreateTable(t2))`, it throws the same `sqlalchemy.exc.ArgumentError`.

**Comment by ynux** [comment] 2020-01-09 14:02
Thanks for reopening. I just tried running the inspector against this column, and it in fact comes back with `'autoincrement': True` , which might confuse both people and code as this is not directly implemented in snowflake-sqlalchemy [https://docs.snowflake.net/manuals/user-guide/sqlalchemy.html#auto-increment-behavior](https://docs.snowflake.net/manuals/user-guide/sqlalchemy.html#auto-increment-behavior)

```
 inspector.get_columns('sequencetable')
[{'name': 'id', 'type': DECIMAL(precision=38, scale=0), 'nullable': False, 'default': None, 'autoincrement': True, 'comment': None, 'primary_key': True}, {'name': 'data', 'type': VARCHAR(length=39), 'nullable': True, 'default': None, 'autoincrement': False, 'comment': None, 'primary_key': False}]
```

**Comment by keller00** [comment] 2020-01-12 00:46
This could be solved by somehow remembering which sequence was used to drive this `autoincrement` column, @smtakeda

**Comment by eddyojb88** [comment] 2021-12-06 21:26
1 year on and this is still unsolved? This is a very basic feature.

**Comment by eddyojb88** [comment] 2021-12-06 21:26
Correction. 2 years on!!

**Comment by ThomasJRyan** [comment] 2022-04-26 18:35
Coming across a similar error as well where when I add in a new row with an auto-incremented primary key and try to flush it I get this error:

```python
FlushError: Instance <Usecase at 0x7f0e68fcdee0> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.
```

Seems there isn't a good fix for this yet

**Closed** 2022-06-03 18:39 UTC
Labels: question, jira

**Comment by sfc-gh-aling** [comment] 2022-06-03 18:52
hey folks, apologize for the late response and thanks for your patience.

we've investigated the issue found the existing code was not doing correctly in **_two_** aspects:

1. The first issue is that when we create a column with `Sequence`, the default value was not set correctly, it should not be set using "autoincrement" which failed to connect the column with the sequence.
       - to fix the issue, we should use "default seq.nextval" to set as the column's default value.
       - for more context please check doc here for "autoincrement" and "default" keyword: https://docs.snowflake.com/en/sql-reference/sql/create-table.html#optional-parameters
2. The second issue is caused by [type affinity check](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/sql/schema.py#L4504-L4511), specifically sqlalchemy is checking whether DECIMAL(NUMBER in snowflake) is a subclass of INTEGER (this is what user hit).
       - In snowflake, INTEGER is synonymous of NUMERIC (DECIMAL), see doc here: https://docs.snowflake.com/en/sql-reference/data-types-numeric.html, when we create a sqlalchemy `Integer` in snowflake, a NUMBER(38, 0) (DECIMAL is sqlalchemy) is created.
       - to fix the issue, we need to customize the affinity check of DECIMAL in which case DECIMAL(38,0) is affinity of INTEGER.

We've fixed the aforementioned issues in the PR https://github.com/snowflakedb/snowflake-sqlalchemy/pull/297 which shall be included in our next please, will keep you informed once the package is out.

**Comment by markfickett** [comment] 2023-08-10 17:02
For posterity, noting that release v1.4.0 on Jul 21, 2022 does mention this is fixed:

> Fixed a bug where insert with autoincrement failed due to incompatible column type affinity https://github.com/snowflakedb/snowflake-sqlalchemy/issues/124.
> Fixed a bug when creating a column with sequence, default value was set incorrectly.
