### ISSUE TITLE
SNOW-846301: SnowflakeDialect.get_columns gives error for columns absent in ischema_names

### ISSUE THREAD

**Issue by mayurinehate** [snowflakedb/snowflake-sqlalchemy#421] opened 2023-06-22 12:31 UTC
1. What version of Python are you using?

    Python 3.10.6

2. What operating system and processor architecture are you using?

    Linux-5.19.0-43-generic-x86_64-with-glibc2.35

3. What are the component versions in the environment (`pip freeze`)?
   
```
    snowflake-connector-python==3.0.4
    snowflake-sqlalchemy==1.4.7
```

4. What did you do?

```
from sqlalchemy import create_engine, inspect
engine = create_engine("snowflake://XXXX")
connection = engine.connect()
connection.execute("create table geospatial_table (id INTEGER, g GEOMETRY);")
inspector = inspect(connection)
columns = inspector.get_columns("geospatial_table")
```

5. What did you expect to see?

    Expected that program would return column details. Instead, received this error - 
    
  ```
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/mayuri/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 680, in get_columns
      schema_columns = self._get_schema_columns(connection, schema, **kw)
    File "<string>", line 2, in _get_schema_columns
    File "/home/mayuri/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 47, in cache
      return fn(self, con, *args, **kw)
    File "/home/mayuri/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 553, in _get_schema_columns
      type_instance = col_type(**col_type_kw)
  TypeError: 'NullType' object is not callable
  ```

**Comment by sfc-gh-dszmolka** [comment] 2024-03-26 10:53
hi and thank you for raising this issue with us and adding the reproduction is really appreciated! this seems to be working now
```python
    columns = inspector.get_columns("geospatial_table")
    print(columns)
```

returns
```
[{'name': 'id', 'type': _CUSTOM_DECIMAL(precision=38, scale=0), 'nullable': True, 'default': None, 'autoincrement': False, 'comment': None, 'primary_key': False}, {'name': 'g', 'type': GEOMETRY(), 'nullable': True, 'default': None, 'autoincrement': False, 'comment': None, 'primary_key': False}]
```

closing for now but let us know please in a comment if you need further help with this

**Closed by sfc-gh-dszmolka** 2024-03-26 10:53 UTC
Labels: bug, status-triage
