### ISSUE TITLE
support comments on table

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [snowflakedb/snowflake-sqlalchemy#135] opened 2019-11-27 21:26 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 2.7.15+

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-4.15.0-65-generic-x86_64-with-Ubuntu-18.04-bionic

3. What are the component versions in the environment (`pip list`)? 
```
Package                       Version  
----------------------------- ---------
alembic                       1.0.11   
APScheduler                   3.6.1    
asn1crypto                    0.24.0   
azure-common                  1.1.23   
azure-nspkg                   3.0.2    
azure-storage-blob            2.1.0    
azure-storage-common          2.1.0    
azure-storage-nspkg           3.1.0    
backports.functools-lru-cache 1.5      
boto3                         1.9.253  
botocore                      1.12.253 
certifi                       2019.9.11
cffi                          1.13.1   
chardet                       3.0.4    
Click                         7.0      
colorlog                      4.0.2    
cryptography                  2.8      
docutils                      0.15.2   
enum34                        1.1.6    
funcsigs                      1.0.2    
future                        0.18.1   
futures                       3.3.0    
gevent                        1.4.0    
greenlet                      0.4.15   
humanize                      0.5.1    
idna                          2.8      
ijson                         2.5.1    
influxdb                      5.2.3    
ipaddress                     1.0.23   
Jinja2                        2.10.3   
jmespath                      0.9.4    
Mako                          1.1.0    
MarkupSafe                    1.1.1    
pip                           19.3.1   
pip-tools                     4.3.0    
pyasn1                        0.4.7    
pyasn1-modules                0.2.7    
pycparser                     2.19     
pycryptodomex                 3.9.0    
PyJWT                         1.7.1    
pyOpenSSL                     19.0.0   
python-dateutil               2.8.0    
python-editor                 1.0.4    
pytz                          2019.3   
requests                      2.22.0   
s3transfer                    0.2.1    
setuptools                    42.0.1   
six                           1.12.0   
snowflake-connector-python    1.9.1    
snowflake-sqlalchemy          1.1.15   
SQLAlchemy                    1.3.10   
tzlocal                       2.0.0    
urllib3                       1.25.6   
wheel                         0.33.6   

```
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I am trying to add comments to tables via sqlalchemy
```

class TableA(Base):

    __tablename__ = 'table_a'
    __table_args__= {
        'comment': ("This table has been deprecated")
    }
    row_id = Column(String(256), primary_key=True)

This generates an alembic revision in which the `comment` is being included
op.create_table('table_id',
    sa.PrimaryKeyConstraint('row_id'),
    comment="This table has been deprecated "
    )

however, the comment is not being included when `CREATE TABLE` sql is produced

CREATE TABLE table_a (
	row_id VARCHAR(256), 
	PRIMARY KEY (row_id)
)

```

5. What did you expect to see?

comment to be included in the CREATE TABLE query

6. What did you see instead?

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by keller00** [comment] 2019-11-27 21:27
Duplicate of #118

**Comment by keller00** [comment] 2019-11-27 21:27
Included in next release, thank you!

**Closed by keller00** 2019-11-27 21:27 UTC
