### ISSUE TITLE
SNOW-679045: _rfc_1738_quote is no longer available in sqlalchemy 1.4.42

### ISSUE THREAD

**Issue by scastria** [snowflakedb/snowflake-sqlalchemy#350] opened 2022-10-16 22:32 UTC
The latest release of sqlalchemy 1.4.42 has renamed all of the rfc 1738 stuff so this import no longer works:  https://github.com/snowflakedb/snowflake-sqlalchemy/blob/be1f7417ee52f29943e082a51d87a5104e78205a/src/snowflake/sqlalchemy/util.py#L8

**Comment by zzzeek** [comment] 2022-10-16 22:57
I'd suggest snowflake just vendor this short function directly.

**Comment by francesco086** [comment] 2022-10-17 08:51
Got this issue and was about to report it, hope it can get fixed soon

**Comment by phillip-parrott** [comment] 2022-10-17 09:30
Put in a fix, hopefully this gets approved 🤞

**Comment by fernandobrito** [comment] 2022-10-17 09:53
+1. Also affected by this.

**Comment by dtpryce** [comment] 2022-10-17 11:09
Also affected ... looks like you should just change the method name imported from `sqlalchemy` https://github.com/sqlalchemy/sqlalchemy/commit/c88bb2167b1c4b39c7f9378b621bb8d429269d90 ?

**Comment by dtpryce** [comment] 2022-10-17 11:10
`_sqla_url_quote` is the new method name

**Comment by phillip-parrott** [comment] 2022-10-17 11:11
that would break everyone on older versions of sqlalchemy, best practice is not to use private functions from other libraries

**Comment by dtpryce** [comment] 2022-10-17 11:14
Yeah fair and agreed, why was it there already ;P

**Comment by zzzeek** [comment] 2022-10-17 12:54
as I mentioned, snowflake should vendor this, it's one line

**Comment by aniket-jain9** [comment] 2022-10-17 13:17
I'm new to this, do anyone have idea, how long will it take to fix this?

**Comment by R2RHONEY** [comment] 2022-10-17 13:58
Also have production issues . Old versions of Snowflake_SQLalchemy 1.2.4  also failing due to dependency on < 2 so collecting 1.42 SQLAlchemy and failing. What is the resolution for this?

**Comment by sfc-gh-achandrasekaran** [comment] 2022-10-17 16:21
We will vendor this fix asap. Thanks folks.

**Comment by strangemonad** [comment] 2022-10-17 18:52
Seems like there's already an open PR? https://github.com/snowflakedb/snowflake-sqlalchemy/pull/351

**Comment by sfc-gh-aling** [comment] 2022-10-17 18:59
yes @strangemonad , we're testing the PR right now to make sure this is the only place which needs a change.

**Comment by sfc-gh-aling** [comment] 2022-10-17 20:26
hey @jonashaag , I think we shall target getting that issue #327  fixed in v 1.4. I'm sorry that I still can't reproduce the #327 issue, if you could share me with details of your test code for reproducing, I would love to prioritize the fix for you.

**Comment by sfc-gh-aling** [comment] 2022-10-18 00:11
hey folks, we have released v1.4.3: https://pypi.org/project/snowflake-sqlalchemy/1.4.3/

please use `pip install snowflake-sqlalchemy --upgrade` to upgrade, let me know if you're still encountering the same issue

**Comment by sfc-gh-aling** [comment] 2022-10-19 17:23
@HankYunDI that's a bit weird, I tested locally, the import is working.

what command did you use to upgrade snowflake-sqlalchemy? also is it possible to import the snowflake-sqlalchemy in your env --`import snowflake.sqlalchemy`?

**Comment by bhavna-a** [comment] 2022-10-28 04:25
@sfc-gh-aling I can only upgrade it to version 1.3.4, can the fix be backported to that version?


```
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement snowflake-sqlalchemy==1.4.3 (from versions: 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.1, 1.3.2, 1.3.3, 1.3.4)
ERROR: No matching distribution found for snowflake-sqlalchemy==1.4.3
```

**Comment by sfc-gh-aling** [comment] 2022-10-31 17:55
hey @bhavna-a , may I ask what platform you're using the how did you set up your python environment?
I haven't seen this error message before and it looks like the listed versions are fixed.. are you downloading packages from pypi?

**Comment by tom-juntunen** [comment] 2022-11-05 01:52
`pip uninstall sqlalchemy` then `pip install 'sqlalchemy < 1.4.42'` worked for me

**Comment by calpaterson** [comment] 2022-11-10 14:26
snowflake-sqlalchemy 1.4.3 fixes this problem for me, for both sqlalchemy 1.4.41 and 1.4.43.  I think this issue can be closed.

**Comment by willh-lw** [comment] 2022-11-10 15:47
Agreed, this resolved the issue for me also.

**Comment by sfc-gh-aling** [comment] 2022-11-10 19:08
thanks guys for your confirmation, closing the issue now.

**Closed by sfc-gh-aling** 2022-11-10 19:08 UTC

**Comment by tushar-swiggy-analytics** [comment] 2023-02-01 06:40
1.4.46 version has the same issue
