### ISSUE TITLE
Yanked 1.4.0 release

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [snowflakedb/snowflake-sqlalchemy#333] opened 2022-08-02 19:58 UTC
Hi people,

We've seen your newly reported issues since the release of version `1.4.0`. Specifically #325 #330 seem to suggest that we introduced some behavior changes in a minor version bump.
We want to correctly support all SQLAlchemy `1.4.0` and upcoming `2.0.0` features even if that means breaking our existing behaviors.
While we re-evaluate the introduced changes we went ahead and yanked this release from PyPi.

Thank you for your understanding and please stay tuned for future releases!

**Comment by sfc-gh-aling** [comment] 2022-08-02 21:31
updates:

- issue: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/330
  - root cause: This is due to `DATE` being accidentally removed from the `ischema_names` in PR: https://github.com/snowflakedb/snowflake-sqlalchemy/pull/314
  - fix plan: add `DATE` back to the map
  - follow up: add tests to cover `ischema_names` such that any breaking changes will be detected

**Comment by kklein** [comment] 2022-08-04 15:45
Thanks for the update! Just to let you know, conda-forge still offers version 1.4.0:
https://anaconda.org/conda-forge/snowflake-sqlalchemy/files

**Comment by sfc-gh-aling** [comment] 2022-08-06 01:12
thanks @kklein for info, I'm afraid conda-forge doesn't provide a way to yank the package as pypi. we will do a patch release soon to fix the issues.

**Comment by sfc-gh-aling** [comment] 2022-08-25 18:26
we have released 1.4.1 which fixed the breaking changes.

for issue https://github.com/snowflakedb/snowflake-sqlalchemy/issues/327, the patch introduced in 1.4 fixed some double percent sign issues, however it is breaking others. I believe it's worth a separate fix once we can reproduce the user issue.

I'm closing the issue now, feel free to reach out any issue in 1.4 is observed, thanks!

**Closed by sfc-gh-aling** 2022-08-25 18:26 UTC

**Comment by jtilly** [comment] 2022-10-17 20:51
>  I'm afraid conda-forge doesn't provide a way to yank the package as pypi. we will do a patch release soon to fix the issues.

Just FYI (probably not relevant anymore), but you can mark packages on conda-forge as broken. Just make a PR at https://github.com/conda-forge/admin-requests/

For this particular case, you would add a single file `broken/snowflake-sqlalchemy-1.4.0.txt` that contains
`noarch/snowflake-sqlalchemy-1.4.0-pyhd8ed1ab_0.tar.bz2`.
